// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1up5iK6RfoOKD3vqhmvyBCDwqwEY9NrI',
    appId: '1:241229525734:web:156ae727ae286a930d8127',
    messagingSenderId: '241229525734',
    projectId: 'prueba-jar',
    authDomain: 'prueba-jar.firebaseapp.com',
    databaseURL: 'https://prueba-jar.firebaseio.com',
    storageBucket: 'prueba-jar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4f-Nqj13mpICJAs_8tD52wQ5xjyKF2Js',
    appId: '1:241229525734:android:68ac74f63eeddcdd0d8127',
    messagingSenderId: '241229525734',
    projectId: 'prueba-jar',
    databaseURL: 'https://prueba-jar.firebaseio.com',
    storageBucket: 'prueba-jar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA025Lf9ajSx1NHR7zLGdtcFLDkW3mbN2M',
    appId: '1:241229525734:ios:c616d93776d4b3670d8127',
    messagingSenderId: '241229525734',
    projectId: 'prueba-jar',
    databaseURL: 'https://prueba-jar.firebaseio.com',
    storageBucket: 'prueba-jar.appspot.com',
    iosClientId: '241229525734-go87264enk2o1fmicg5gf64s29bv7jep.apps.googleusercontent.com',
    iosBundleId: 'com.theapp.visionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA025Lf9ajSx1NHR7zLGdtcFLDkW3mbN2M',
    appId: '1:241229525734:ios:f871f1e884e2e74c0d8127',
    messagingSenderId: '241229525734',
    projectId: 'prueba-jar',
    databaseURL: 'https://prueba-jar.firebaseio.com',
    storageBucket: 'prueba-jar.appspot.com',
    iosClientId: '241229525734-b4lue2f64n8gp5kkmbqbimkfkn837sp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1up5iK6RfoOKD3vqhmvyBCDwqwEY9NrI',
    appId: '1:241229525734:web:46835f8f02b19bde0d8127',
    messagingSenderId: '241229525734',
    projectId: 'prueba-jar',
    authDomain: 'prueba-jar.firebaseapp.com',
    databaseURL: 'https://prueba-jar.firebaseio.com',
    storageBucket: 'prueba-jar.appspot.com',
  );
}